/**
 * Export helpers: district forecasts (CSV, GeoJSON) from the live cycle, and CAP 1.2 alerts (XML, JSON).
 */

import type { AppAlert } from "@/data/alerts";
import type { Cycle, ForecastRec } from "@/data/cycle";
import type { AlertLevel } from "./imd";

function download(content: string, filename: string, mime: string) {
  const url = URL.createObjectURL(new Blob([content], { type: mime }));
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

const stamp = (c: Cycle) => c.issue.init_utc.slice(0, 13).replace(/[-:]/g, "");

function csvCell(v: string | number | null | undefined): string {
  if (v === null || v === undefined) return "";
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function rainRows(c: Cycle, lead: number): { p: Cycle["points"][number]; f: ForecastRec }[] {
  const byPoint = new Map(c.forecasts.filter((f) => f.var === "rain" && f.lead === lead).map((f) => [f.point_id, f]));
  return c.points.flatMap((p) => (byPoint.has(p.id) ? [{ p, f: byPoint.get(p.id)! }] : []));
}

export function exportDistrictsCsv(c: Cycle, lead: number) {
  const live = c.sources.filter((s) => s.live).map((s) => s.id);
  const headers = [
    "district_id", "district", "region", "lat", "lon", "valid_date", "lead_day", "run_init_utc",
    "blend_mm", "p10_mm", "p90_mm", "equal_mean_mm", "model_spread_sd_mm", "method",
    "p_ge_64_5", "p_ge_115_6", "p_ge_204_5", "alert_level",
    ...live.map((s) => `forecast_${s}`), ...live.map((s) => `weight_${s}`),
  ];
  const rows = rainRows(c, lead).map(({ p, f }) => [
    p.id, p.name, p.region, p.lat, p.lon, f.date, lead, c.issue.init_utc,
    f.blend, f.p10, f.p90, f.equal_mean, f.spread_sd, f.method,
    f.prob?.["64.5"], f.prob?.["115.6"], f.prob?.["204.5"], f.alert_level ?? "",
    ...live.map((s) => f.values[s]), ...live.map((s) => f.weights[s]),
  ]);
  const csv = "﻿" + [headers, ...rows].map((r) => r.map(csvCell).join(",")).join("\r\n");
  download(csv, `bharosa_districts_${stamp(c)}_D${lead}.csv`, "text/csv;charset=utf-8");
}

export function exportDistrictsGeoJson(c: Cycle, lead: number) {
  const geojson = {
    type: "FeatureCollection",
    metadata: { run_init_utc: c.issue.init_utc, generated_at: c.generated_at, lead_day: lead, method: c.method.name, attribution: c.attribution },
    features: rainRows(c, lead).map(({ p, f }) => ({
      type: "Feature",
      geometry: { type: "Point", coordinates: [p.lon, p.lat] },
      properties: {
        id: p.id, name: p.name, region: p.region, valid_date: f.date,
        blend_mm: f.blend, p10_mm: f.p10, p90_mm: f.p90, equal_mean_mm: f.equal_mean,
        prob: f.prob, alert_level: f.alert_level ?? null, weights: f.weights, forecasts: f.values,
      },
    })),
  };
  download(JSON.stringify(geojson, null, 2), `bharosa_districts_${stamp(c)}_D${lead}.geojson`, "application/geo+json");
}

/* ── CAP 1.2 (OASIS Common Alerting Protocol) ───────────────── */

const CAP_SEVERITY: Record<AlertLevel, string> = { Red: "Extreme", Orange: "Severe", Yellow: "Moderate" };
const CAP_URGENCY: Record<AlertLevel, string> = { Red: "Immediate", Orange: "Expected", Yellow: "Future" };

// CAP requires timestamps without milliseconds and with an explicit offset
const capTime = (d: Date) => d.toISOString().replace(/\.\d{3}Z$/, "+00:00");

export interface CapContext {
  /** Rain day label: the 24 h ending 08:30 IST on this date. */
  validDate: string;
  lead: number;
  label: string;
}

function buildCap(alerts: AppAlert[], ctx: CapContext) {
  const sent = new Date();
  const expires = new Date(`${ctx.validDate}T08:30:00+05:30`);
  const onset = new Date(expires.getTime() - 86_400_000);
  return {
    identifier: `BHAROSA-${ctx.label}-D${ctx.lead}-${sent.getTime()}`,
    sender: "bharosa-prototype.local",
    sent: capTime(sent),
    status: "Exercise", // prototype system, not an operational warning
    msgType: "Alert",
    scope: "Public",
    note: "Generated by the Bharosa prototype from live multi-model forecasts. Not an official IMD warning.",
    info: alerts.map((a) => ({
      language: "en-IN",
      category: "Met",
      event: a.level === "Red" ? "Flash Flood / Extremely Heavy Rainfall" : "Heavy Rainfall",
      urgency: CAP_URGENCY[a.level],
      severity: CAP_SEVERITY[a.level],
      certainty: "Likely",
      onset: capTime(onset),
      expires: capTime(expires),
      senderName: "Bharosa Multi-Model Blending Engine",
      headline: `${a.level.toUpperCase()}: ${a.headline}`,
      description: a.detail,
      parameters: [["alert_id", a.id], ["blend_mm", a.valueMm.toFixed(1)]] as [string, string][],
      area: { areaDesc: `${a.place}, ${a.region}`, circle: `${a.lat},${a.lng} 25` },
    })),
  };
}

const xmlEscape = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export function exportCapXml(alerts: AppAlert[], ctx: CapContext) {
  const cap = buildCap(alerts, ctx);
  const tag = (name: string, value: string, indent: string) => `${indent}<${name}>${xmlEscape(value)}</${name}>`;
  const infoXml = cap.info.map((i) =>
    [
      "  <info>",
      ...(["language", "category", "event", "urgency", "severity", "certainty", "onset", "expires", "senderName", "headline", "description"] as const).map((k) =>
        tag(k, i[k], "    ")
      ),
      ...i.parameters.map(([k, v]) => ["    <parameter>", tag("valueName", k, "      "), tag("value", v, "      "), "    </parameter>"].join("\n")),
      "    <area>",
      tag("areaDesc", i.area.areaDesc, "      "),
      tag("circle", i.area.circle, "      "),
      "    </area>",
      "  </info>",
    ].join("\n")
  );
  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<alert xmlns="urn:oasis:names:tc:emergency:cap:1.2">',
    ...(["identifier", "sender", "sent", "status", "msgType", "scope", "note"] as const).map((k) => tag(k, cap[k], "  ")),
    ...infoXml,
    "</alert>",
  ].join("\n");
  download(xml, `bharosa_alerts_${ctx.label}_D${ctx.lead}_cap.xml`, "application/xml");
}

export function exportCapJson(alerts: AppAlert[], ctx: CapContext) {
  const cap = buildCap(alerts, ctx);
  const json = {
    ...cap,
    info: cap.info.map(({ parameters, ...rest }) => ({ ...rest, parameter: parameters.map(([valueName, value]) => ({ valueName, value })) })),
  };
  download(JSON.stringify(json, null, 2), `bharosa_alerts_${ctx.label}_D${ctx.lead}_cap.json`, "application/json");
}
