/**
 * Export helpers for AtmosFusion: CSV, GeoJSON, and CAP 1.2 (XML + JSON).
 */

import type { RegionForecast, AlertLevel } from "@/types/weather";
import type { AppAlert } from "@/data/alerts";

function download(content: string, filename: string, mime: string) {
  const url = URL.createObjectURL(new Blob([content], { type: mime }));
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

const baseName = (f: RegionForecast) => `atmosfusion_${f.region_id}_D${f.lead_day}`;

function csvCell(v: string | number | null): string {
  if (v === null) return "";
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function exportCsv(forecast: RegionForecast) {
  const headers = [
    "station_id",
    "name",
    "lat",
    "lng",
    "elevation_m",
    "terrain",
    "observed_rain_24h_mm",
    "consensus_blend_mm",
    "simple_average_mm",
    "p90_mm",
    "spread_max_min_mm",
    "p_heavy_ge_64_5",
    "p_very_heavy_ge_115_6",
    "p_extreme_ge_204_5",
    "dominant_model",
    "dominant_family",
    "alert_level",
    "alert_message",
    ...Object.keys(forecast.stations[0]?.assigned_weights ?? {}).map((m) => `weight_${m}`),
  ];

  const rows = forecast.stations.map((s) => [
    s.id,
    s.name,
    s.lat,
    s.lng,
    s.elevation_m,
    s.terrain_type,
    s.observed_rain_24h,
    s.consensus_blend,
    s.simple_average,
    s.worst_case_90th,
    s.disagreement_index,
    s.p_heavy_rain,
    s.p_very_heavy,
    s.p_extremely_heavy,
    s.dominant_model,
    s.dominant_family,
    s.alert_level,
    s.active_alert,
    ...Object.values(s.assigned_weights),
  ]);

  // BOM so Excel opens UTF-8 (≥, °) correctly
  const csv = "﻿" + [headers, ...rows].map((r) => r.map(csvCell).join(",")).join("\r\n");
  download(csv, `${baseName(forecast)}.csv`, "text/csv;charset=utf-8");
}

export function exportGeoJson(forecast: RegionForecast) {
  const geojson = {
    type: "FeatureCollection",
    metadata: {
      region_id: forecast.region_id,
      region_name: forecast.region_name,
      lead_day: forecast.lead_day,
      regime: forecast.regime,
      generated_at: new Date().toISOString(),
    },
    features: forecast.stations.map((s) => ({
      type: "Feature",
      geometry: { type: "Point", coordinates: [s.lng, s.lat, s.elevation_m] },
      properties: {
        id: s.id,
        name: s.name,
        terrain: s.terrain_type,
        coverage_radius_km: s.coverage_radius_km,
        consensus_blend_mm: s.consensus_blend,
        simple_average_mm: s.simple_average,
        p90_mm: s.worst_case_90th,
        spread_mm: s.disagreement_index,
        p_heavy_rain: s.p_heavy_rain,
        p_very_heavy: s.p_very_heavy,
        p_extremely_heavy: s.p_extremely_heavy,
        dominant_model: s.dominant_model,
        weights: s.assigned_weights,
        alert_level: s.alert_level,
        active_alert: s.active_alert,
      },
    })),
  };
  download(JSON.stringify(geojson, null, 2), `${baseName(forecast)}.geojson`, "application/geo+json");
}

/* ── CAP 1.2 (OASIS Common Alerting Protocol) ───────────────── */

const CAP_SEVERITY: Record<AlertLevel, string> = { Red: "Extreme", Orange: "Severe", Yellow: "Moderate" };
const CAP_URGENCY: Record<AlertLevel, string> = { Red: "Immediate", Orange: "Expected", Yellow: "Future" };

// CAP requires timestamps without milliseconds and with an explicit offset
const capTime = (d: Date) => d.toISOString().replace(/\.\d{3}Z$/, "+00:00");

export interface CapContext {
  /** Forecast valid date (YYYY-MM-DD) and lead day, used for onset/expiry. */
  validDate: string;
  lead: number;
  label: string;
}

function buildCap(alerts: AppAlert[], ctx: CapContext) {
  const sent = new Date();
  const onset = new Date(`${ctx.validDate}T00:00:00+05:30`);
  const expires = new Date(onset.getTime() + 86_400_000);
  return {
    identifier: `ATMOSFUSION-${ctx.label.toUpperCase().replace(/[^A-Z0-9]+/g, "-")}-D${ctx.lead}-${sent.getTime()}`,
    sender: "atmosfusion-prototype.local",
    sent: capTime(sent),
    status: "Exercise", // prototype system — not an operational warning
    msgType: "Alert",
    scope: "Public",
    note: "Generated by the AtmosFusion prototype. Not an official IMD warning.",
    info: alerts.map((a) => ({
      language: "en-IN",
      category: "Met",
      event: a.level === "Red" ? "Flash Flood / Extremely Heavy Rainfall" : "Heavy Rainfall",
      urgency: CAP_URGENCY[a.level],
      severity: CAP_SEVERITY[a.level],
      certainty: "Likely",
      onset: capTime(onset),
      expires: capTime(expires),
      senderName: "AtmosFusion Multi-Model Blending Engine",
      headline: `${a.level.toUpperCase()} — ${a.headline}`,
      description: a.detail,
      parameters: [
        ["alert_id", a.id],
        ["source", a.source],
        ["value_mm", a.valueMm.toFixed(1)],
      ] as [string, string][],
      area: {
        areaDesc: a.place,
        // Stations have a point: CAP circle is "lat,lon radius_km"
        circle: a.lat !== undefined && a.lng !== undefined ? `${a.lat},${a.lng} 12` : undefined,
      },
    })),
  };
}

const xmlEscape = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export function exportCapXml(alerts: AppAlert[], ctx: CapContext) {
  const cap = buildCap(alerts, ctx);
  const tag = (name: string, value: string, indent: string) => `${indent}<${name}>${xmlEscape(value)}</${name}>`;
  const infoXml = cap.info.map((i) =>
    [
      "  <info>",
      tag("language", i.language, "    "),
      tag("category", i.category, "    "),
      tag("event", i.event, "    "),
      tag("urgency", i.urgency, "    "),
      tag("severity", i.severity, "    "),
      tag("certainty", i.certainty, "    "),
      tag("onset", i.onset, "    "),
      tag("expires", i.expires, "    "),
      tag("senderName", i.senderName, "    "),
      tag("headline", i.headline, "    "),
      tag("description", i.description, "    "),
      ...i.parameters.map(([k, v]) => ["    <parameter>", tag("valueName", k, "      "), tag("value", v, "      "), "    </parameter>"].join("\n")),
      "    <area>",
      tag("areaDesc", i.area.areaDesc, "      "),
      ...(i.area.circle ? [tag("circle", i.area.circle, "      ")] : []),
      "    </area>",
      "  </info>",
    ].join("\n")
  );
  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<alert xmlns="urn:oasis:names:tc:emergency:cap:1.2">',
    tag("identifier", cap.identifier, "  "),
    tag("sender", cap.sender, "  "),
    tag("sent", cap.sent, "  "),
    tag("status", cap.status, "  "),
    tag("msgType", cap.msgType, "  "),
    tag("scope", cap.scope, "  "),
    tag("note", cap.note, "  "),
    ...infoXml,
    "</alert>",
  ].join("\n");
  download(xml, `atmosfusion_alerts_${ctx.label}_D${ctx.lead}_cap.xml`, "application/xml");
}

export function exportCapJson(alerts: AppAlert[], ctx: CapContext) {
  const cap = buildCap(alerts, ctx);
  const json = {
    ...cap,
    info: cap.info.map(({ parameters, area, ...rest }) => ({
      ...rest,
      parameter: parameters.map(([valueName, value]) => ({ valueName, value })),
      area: area.circle ? area : { areaDesc: area.areaDesc },
    })),
  };
  download(JSON.stringify(json, null, 2), `atmosfusion_alerts_${ctx.label}_D${ctx.lead}_cap.json`, "application/json");
}
